name: Publish Client
on:
  repository_dispatch:
    types: [notify-client-generator]
jobs:
  notifyClientGenerator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: OPENAPIVERSION=${{ github.event.client_payload.openAPIVersion }} npm run generate
  publishToNpm:
    runs-on: ubuntu-latest
    needs: notifyClientGenerator
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm version ${{ github.event.client_payload.openAPIVersion }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
