name: Publish Client
on:
  repository_dispatch:
    types: [notify-client-generator]
jobs:
  handleNotifyClientGenerator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm version ${{ github.event.client_payload.openAPIVersion }} --no-commit-hooks --no-git-tag-version
      - run: OPENAPIVERSION=${{ github.event.client_payload.openAPIVersion }} npm run generate
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit -am "Generated new client"
          git push
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
